site_name: "ROADMAPPERS"
repo_name: Roadmappers.ru
repo_url: https://github.com/halltape/HalltapeRoadmapDE
site_url: https://roadmappers.ru
copyright: MIT

# Явное, лаконичное меню
nav:
  - В начало: README.md
  - BootCamp: /#bootcamp-data-engineer
  - Деньги: /#0
  - Кто такой DE: /#1
  - Курсы: /#2
  - Git: /#3-github-git
  - Linux/Terminal: /#4-linux-terminal
  - DWH: /#5-data-warehouse
  - NF: /#6
  - Модели Данных: /#7
  - DataVault: /#8-data-vault-hub-satellite-link
  - Индексы: /#9
  - Docker: /#10-docker
  - Hadoop: /#11-hadoop
  - Airflow: /#12-airflow
  - Greenplum: /#13-greenplum
  - Clickhosue: /#14-clickhouse
  - Spark: /#15-spark
  - dbt: /#16-dbt-data-build-tool
  - Kafka: /#17-apache-kafka
  - Pet Project: /#18-pet-project
  - Собесы: /#19-c
  - Резюме и Работа: /#20
  - Кейсы: /#21
  - Полезные ссылки: /#22

theme:
  name: material
  palette:
    scheme: slate  # тёмная тема (можно убрать для светлой)
  font:
    text: Roboto
    code: Fira Mono
  code:
    highlight_theme: dracula
  logo: _frontend/images/logo_v2.svg

# Только свой CSS
extra_css:
  - _frontend/css/custom.css

extra_javascript:
  - _frontend/js/toc-home.js
  - _frontend/js/scroll-to-top.js


markdown_extensions:
  - admonition
  - codehilite
  - tables
  - footnotes